---
resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook_url))

- name: page-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-tutorials/tutorials.git
    branch: main
    username: ((github_username))
    password: ((github_password))
    paths: [landing-page/*]

- name: ci-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-tutorials/tutorials.git
    branch: main
    username: ((github_username))
    password: ((github_password))
    paths: [ci/*]

- name: version
  type: semver
  source:
    driver: s3
    initial_version: 0.0.1
    bucket: tutorials.cff.rscale.io
    key: landing-page/version
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-west-2

- name: rc
  type: s3
  source:
    regexp: landing-page/rc/landing-page-(.*).zip
    bucket: tutorials.cff.rscale.io
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-west-2

- name: artifact
  type: s3
  source:
    regexp: landing-page/landing-page-(.*).zip
    bucket: tutorials.cff.rscale.io
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    region_name: us-west-2

- name: staging-manifest
  type: git
  source:
    uri: https://github.com/cloudfoundry-tutorials/tutorials.git
    branch: main
    username: ((github_username))
    password: ((github_password))
    paths: [landing-page/staging-manifest.yml]

- name: deploy-staging
  type: cf
  source:
    api: ((cf_api_staging))
    username: ((cf_username_staging))
    password: ((cf_password_staging))
    organization: ((cf_org_staging))
    space: ((cf_space_staging))

- name: production-manifest
  type: git
  source:
    uri: https://github.com/cloudfoundry-tutorials/tutorials.git
    branch: main
    username: ((github_username))
    password: ((github_password))
    paths: [landing-page/production-manifest.yml]

- name: deploy-production
  type: cf
  source:
    api: ((cf_api_production))
    username: ((cf_username_production))
    password: ((cf_password_production))
    organization: ((cf_org_production))
    space: ((cf_space_production))

jobs:

- name: build
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: page-source
      trigger: true
      params: {depth: 1}
    - get: ci-source
      params: {depth: 1}
    - get: version
      params: {pre: rc}
  - task: build
    file: ci-source/ci/landing/tasks/build.yml
  - put: rc
    params: {file: site/*.zip}
  - put: version
    params: {file: version/version}

- name: deploy-staging
  serial_groups: [staging]
  plan:
  - in_parallel:
    - get: rc
      trigger: true
      passed: [build]
    - get: staging-manifest
      trigger: true
      params: {depth: 1}
  - put: deploy-staging
    params:
      current_app_name: landing-page
      manifest:  staging-manifest/landing-page/staging-manifest.yml
      path: rc/*.zip
  on_success:
    put: slack
    params:
      username: "rscale-ci"
      text: "CFF tutorials landing page deployed to staging at https://cff-tutorials-staging.kubecf.rscale.dev"
  on_failure:
    put: slack
    params:
      username: "rscale-ci"
      text: "FAILED to deploy CFF tutorials landing page to staging: https://ci.rscale.dev/teams/cff-tutorials/pipelines/landing-page"

- name: promote
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: rc
      passed: [deploy-staging]
    - get: version
      params: {bump: final}
    - get: ci-source
      params: {depth: 1}   
  - task: promote
    file: ci-source/ci/landing/tasks/promote.yml
  - put: artifact
    params: {file: artifact/*.zip}
  - put: version
    params: {bump: patch}

- name: deploy-production
  serial_groups: [staging]
  plan:
  - in_parallel:
    - get: artifact
      trigger: true
      passed: [promote]
    - get: production-manifest
      trigger: true
      params: {depth: 1}
  - put: deploy-production
    params:
      current_app_name: landing-page
      manifest:  production-manifest/landing-page/production-manifest.yml
      path: artifact/*.zip
  on_success:
    put: slack
    params:
      username: "rscale-ci"
      text: "CFF tutorials landing page deployed to production at https://tutorials.cloudfoundry.org"
  on_failure:
    put: slack
    params:
      username: "rscale-ci"
      text: "FAILED to deploy CFF tutorials landing page to production: https://ci.aws.rscale.io/teams/cff-tutorials/pipelines/landing-page"


# - name: minor
#   serial_groups: [version]
#   plan:
#     - put: version
#       params: {bump: minor, pre: rc}

# - name: major
#   serial_groups: [version]
#   plan:
#     - put: version
#       params: {bump: major, pre: rc}
